### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by jdb-vsn** [jd-boyd/irccat3#3]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 842, in emit
Traceback (most recent call last):
  File "/usr/local/bin/irccat3", line 9, in <module>
    load_entry_point('irccat3==0.1', 'console_scripts', 'irccat3')()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/main.py", line 54, in main
    c.start()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1212, in start
    self.ircobj.process_forever()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 264, in process_forever
    self.process_once(timeout)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 38, in process_loop
    self.ircobj.process_once()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 245, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 210, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 643, in process_data
    self._handle_event(Event(command, NickMask(prefix), target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 647, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 384, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1175, in _dispatcher
    method(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 31, in on_join
    self.process_loop()
  File "/usr/local/lib/python2.7/dist-packages/irccat3/bot.py", line 40, in process_loop
    self.l.wait_and_handle(0.5)
  File "/usr/local/lib/python2.7/dist-packages/irccat3/listener.py", line 70, in wait_and_handle
    log.error("Socket request error: %r %r", request, client_address)
  File "/usr/lib/python2.7/logging/__init__.py", line 1158, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1250, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1260, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1300, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 744, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 870, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 797, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
RuntimeError: maximum recursion depth exceeded
```

**Comment by jd-boyd** [comment]
I didn't record how to recreate this, so I'm closing it.
